### PR TITLE
Update to use Bootlint 0.11.0

### LINKED ISSUE #48: Update for Bootlint 0.11
And maybe update any other deps along the way too.

### PR DESCRIPTION
**Pull request by hnrch02**
Closes #48.

### CODE REVIEW

**Comment by zacechola** [comment]
This is great since I'm on vacation and didn't bring my laptop. lol

I might need to give you permission to tag a release and use the twbs account to publish to npm. 

cc @cvrebert

**Comment by cvrebert** [comment]
@zacechola While we're at it, could you please add me to the Collaborators list for this GitHub repo?

**Comment by zacechola** [comment]
Sure thing.

**Comment by cvrebert** [comment]
Also relatedly, what do you think about moving this repo under the [twbs org](https://github.com/twbs) (as `twbs/grunt-bootlint`)?
I think the npm download rank/count has proven that this project is viable in terms of user/community interest, and I hope/believe the rest of the Twbs team agrees that you've passed the "is a nice person to work with" test such that we'd be happy to fully officially associate the Twbs brand with you and your project.

**Comment by zacechola** [comment]
Yeah I think that it actually makes more sense as part of the twbs family.

**Comment by cvrebert** [comment]
Great! Just sent you an invitation to the org.

**Comment by zacechola** [comment]
Looks like I got that email and then it was followed by a cancellation email.

**Comment by cvrebert** [comment]
Weird. Just sent another one.

**Comment by zacechola** [comment]
Got it.

**Comment by cvrebert** [comment]
Okay, if I read the GitHub docs correctly, you should now be able to transfer this repo to twbs via its Settings page.

**Comment by zacechola** [comment]
Ok. Done. I'm going to DisneyWorld. :rocket:

**Comment by cvrebert** [comment]
Have wonderful time! :tada:

**Pull request merged**
